plugins {
    id 'java'
}

group = 'praktikum'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.junit.jupiter:junit-jupiter:5.11.3'
    implementation 'org.seleniumhq.selenium:selenium-java:4.25.0'
    implementation 'io.github.bonigarcia:webdrivermanager:5.9.2'
}

test {
    useJUnitPlatform()
    systemProperties System.getProperties()
}
